services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=project
    volumes:
      - db_data:/var/lib/postgresql/data

  flask1:
    build: 
      context: .
      dockerfile: app1/dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app1:/app
  
  flask2:
    build:
      context: .
      dockerfile: app2/dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app2:/app

  flask3:
    build:
      context: .
      dockerfile: app3/dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - flask1
      - flask2
    env_file:
      - .env
    volumes:
      - ./app3:/app

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db_data:
