FROM python:latest
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5003
WORKDIR /app
COPY ./app3 /app/
COPY app3/requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5003
CMD ["flask", "run"]