FROM python:latest
WORKDIR /app
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5001
COPY ./app1 /app
COPY app1/requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5001
CMD ["flask", "run"]