FROM python:latest
WORKDIR /app
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5002
COPY ./app2 /app
COPY app2/requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5002
CMD ["flask", "run"]